### ISSUE TITLE
图片90度旋转后可视框怎么调整占满图片？？

### ISSUE THREAD

**Issue by 15120822558** [advanced-cropper/vue-advanced-cropper#208]
图片90度旋转后可视框怎么调整占满图片？？
图片90度旋转后可视框怎么调整占满图片？？
图片90度旋转后可视框怎么调整占满图片？？

**Comment by 15120822558** [comment]
上传不了图片，就是有一个剪切框。
想在图片旋转90度的时候，剪切框一直都是剪切整张图片的区域的，
或者去掉剪切框直接可以预览整张图片

**Comment by Norserium** [comment]
Translate to English:

> I can't upload the picture, there is a clipping box.
When the picture is rotated by 90 degrees, the clipping box will always clip the entire picture area.
Or remove the cutout box to preview the whole picture directly

The translator didn't help here, I still don't understand the issue. Let's use images to clarify your issue. Could you illustrate your problem?

**Comment by Norserium** [comment]
@15120822558, any news?

**Comment by Norserium** [comment]
@15120822558, I close issue, feel free to reopen it.

**Comment by stanleyxu2005** [comment]
I'm facing the same issue here. 

Just take this official demo as example
https://codesandbox.io/s/vue-advanced-cropper-preview-experimental-fixed-aspect-ratio-eo9ed?file=/src/App.vue

The image is width=540, height=841 (rectangle)
After the image is rotated, the visiable area becomes a square. 


![image](https://user-images.githubusercontent.com/5162687/205306475-fed3568b-2d2c-456c-9768-2ef47fcc4a5c.png)
![image](https://user-images.githubusercontent.com/5162687/205306596-a7eea0a4-a6e0-452b-92c9-080cd32ff0e2.png)

Is it possible to make the image to be shown as "contain" mode, so that it is still show the full image, just like this?
![image](https://user-images.githubusercontent.com/5162687/205307326-baeb55fe-a13b-4933-8b3f-0dcbfb95d788.png)
